# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-04 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(blank=True, max_length=200, verbose_name='Транслит'),
        ),
    ]
