# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-08 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_hashtag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='hash_tag',
            field=models.ManyToManyField(to='home.HashTag'),
        ),
    ]
