# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-10 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_post_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Post')),
            ],
            options={
                'db_table': 'ArticleStatistic',
            },
        ),
    ]
